### ISSUE TITLE
Extension not finding install on remote environment

### ISSUE THREAD

**Issue by mermerico** [run-ai/vscode-genv#7]
Hi,

I'm attempting to try out this extension in a remote environment (hosted using [Coder](https://coder.com/)). I've installed genv using pip and confirmed that it works. However, under "active environments" the extension believes that genv is not installed. If I hit "Install", I get a popup saying that it is attempting to install genv and I see another line containing `eval "$(genv shell --init)"` is added to my .bashrc, but then nothing happens. I wasn't able to find any logs in VSCode's output tab. How can I diagnose this issue?

**Comment by rotenbergrr** [comment]
hey @mermerico and thanks for reaching out!

I tried to reproduce the issue and unfortunately in my setup installation works, so I have a few questions.

1. are you using any environment management software like pyenv, Conda or any other?
4. how did you install Genv in the first place on the remote host? is is over SSH in an external terminal, or one of the terminals within vscode?
5. after installing Genv using `pip`, does the command `genv --help` work for you?
6. in vscode, after you press the installation button in the GUI, does `genv --help` work for you?

**Comment by mermerico** [comment]
Huh, I went to look into this more today and it seems to work. Maybe the solution was to fully disconnect and reconnect to the host?

**Comment by rotenbergrr** [comment]
happy to hear!
not sure about the reason though.

lmk if you encounter it once again
