### ISSUE TITLE
No module named 'fcntl'

### ISSUE THREAD

**Issue by hurui79** [run-ai/vscode-genv#8]
when in run genv --help  on windows 10
![image](https://github.com/run-ai/vscode-genv/assets/16483840/67633eae-03d0-47eb-9338-a820189f09e9)

**Comment by rotenbergrr** [comment]
hi @hurui79 thanks for reaching out!

unfortunately, Genv does not support Windows systems.

**Comment by hurui79** [comment]
> hi @hurui79 thanks for reaching out!
> 
> unfortunately, Genv does not support Windows systems.

。。。。That's exactly what I'm worried about！  
![23BD248A](https://github.com/run-ai/vscode-genv/assets/16483840/cd301afe-a5e4-477e-b33f-a66e887a8a0d)
